language: python
python:
    - "2.7"
# Command to install dependencies
install:
    - python setup.py sdist
    - pip install dist/jasmin-0.4.0-alpha.tar.gz
# Commands to run tests:
script:
    # Service startup test:
    - sudo ln -s /home/travis/virtualenv/python2.7.8/bin/twistd /usr/bin/;sudo /etc/init.d/jasmin start
    - sleep 20
    # Cleaning before going for further tests
    - sudo /etc/init.d/jasmin stop;sudo rm -f /var/log/jasmin/*;sudo rm -f /etc/jasmin/store/*
    # Trial tests and coverage:
    - sudo chmod -R 777 /var/log/jasmin /etc/jasmin/store
    - coverage run `which trial` jasmin
    # Docs building test:
    - cd misc/doc;make html;cd ../../
    # Report coverage:
    - coverage report --omit=/usr/*,/home/travis/virtualenv/*
    # Pylint code analysis and rating:
    - ./misc/pylint/run.sh
services:
    - rabbitmq
    - redis-server
before_script:
    # Test requirements:
    - pip install -r test-requirements
    # pylint requirements:
    - sudo apt-get install -qq pylint bc
    - export PYLINTRC=./misc/pylint/pylintrc
    - chmod +x ./misc/pylint/run.sh
before_install:
    - sudo apt-get update -qq
    # jasmin requirement:
    - sudo apt-get install -qq python-dev libffi-dev libssl-dev
    - sudo useradd jasmin
    - sudo ln -s /etc/jasmin/init-script/jasmin /etc/init.d/
    - sudo mkdir -p /var/log/jasmin /etc/jasmin/resource /etc/jasmin/init-script /etc/jasmin/store /var/run/jasmin
    - sudo chown `whoami` /etc/jasmin /etc/jasmin/resource /etc/jasmin/init-script
    - sudo chown jasmin. /var/log/jasmin /etc/jasmin/store /var/run/jasmin