language: python
python:
    - "2.7"
# Command to install dependencies
install:
    - pip install -r requirements
    - export PYTHONPATH=$PYTHONPATH:/home/travis/build/fourat
# Commands to run tests
script:
    # Normal tests
    - coverage run `which trial` jasmin
    # Docs building test
    - cd misc/doc;make html
    # Report coverage
    - cd ../../;coverage report --omit=/usr/*,/home/travis/virtualenv/*
services:
    - rabbitmq
    - redis-server
before_script:
    - sudo mkdir /var/log/jasmin
    - sudo chown `whoami` /var/log/jasmin
    - sudo ln -s `pwd`/misc/config /etc/jasmin
    - sudo chown `whoami` /etc/jasmin/store
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-dev
