language: python
python:
    - "2.6"
    - "2.7"
# Command to install dependencies
install: "pip install -r REQUIREMENTS"
# Commands to run tests
script:
    # Normal tests
    - trial jasmin
    # Docs building test
    - cd misc/docs;make html
services:
    - rabbitmq
    - redis-server
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install python-twisted
