sudo: false
language: python
python:
    - '2.7'
# Command to install dependencies
install:
    - python setup.py sdist
    - pip install dist/jasmin-0.7b0.tar.gz
    - cp misc/config/init-script/jasmind-ubuntu ~/jasmin/etc/init.d/jasmind
# Commands to run tests:
script:
    # Service startup test:
    - ~/jasmin/etc/init.d/jasmind start
    - sleep 2
    - ~/jasmin/etc/init.d/jasmind status
    # Stop service:
    - ~/jasmin/etc/init.d/jasmind stop
    # Cleaning before going for further tests:
    - rm -f ~/jasmin/var/log/jasmin/*;rm -f ~/jasmin/etc/jasmin/store/*
    # Trial tests and coverage:
    - coverage run `which trial` jasmin
    # Docs building test:
    - cd misc/doc;make html;cd ../../
    # Report coverage:
    - ls -l /home/travis
    - coverage report --omit=/usr/*,/home/travis/virtualenv/*
    # Pylint code analysis and rating:
    - cd ./misc/pylint; ./run.sh
services:
    - rabbitmq
    - redis-server
before_script:
    # Test requirements:
    - pip install -r test-requirements
    - chmod +x ./misc/pylint/run.sh
before_install:
    - virtualenv venv
    - source venv/bin/activate
    - mkdir -p ~/jasmin/var/log/jasmin
    - mkdir -p ~/jasmin/var/run/jasmin
    - mkdir -p ~/jasmin/etc/jasmin/resource
    - mkdir -p ~/jasmin/etc/jasmin/init-script
    - mkdir -p ~/jasmin/etc/jasmin/store
    - mkdir -p ~/jasmin/etc/init.d
    - chmod -R 777 ~/jasmin/var/log/jasmin ~/jasmin/etc/jasmin/store
addons:
  apt:
    packages:
    # jasmin installation requirement:
    # As documented here http://docs.jasminsms.com/en/latest/installation/index.html
    - python-dev
    - libffi-dev
    - libssl-dev
    - pylint
    - bc
notifications:
    slack:
        secure: guCY7vL67vUhvNYLzInV/EIPMZ7ciq+/s0UlfmKvGYrjIMwXdgfshgKXdHF194eQ9+f0dF8ea1P1/aGqCE4Q4ULPZ555FbftNy/bVLfUPn01+odorAux3rVNq4ezX2QlQc06DpVS2r7U+grM+MQtNdRjoZIuAeipp3YRhyyuIr8=
