language: python
python:
    - "2.6"
    - "2.7"
# command to install dependencies
install: "pip install -r REQUIREMENTS"
# command to run tests
script: trial jasmin
services:
    - rabbitmq
    - redis-server
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install python-twisted python-pip
