language: python
python:
    - "2.7"
# Command to install dependencies
install:
    - pip install -r requirements
    - export PYTHONPATH=$PYTHONPATH:$(cd `pwd`;cd ..;pwd)
# Commands to run tests
script:
    # Normal tests
    - coverage run `which trial` jasmin
    # Docs building test
    - cd misc/doc;make html
    - cd ../../
    # Pylint code analysis and rating
    - export PYLINTRC=./.pylintrc
    - pylint jasmin|tee /dev/stderr > /tmp/pylint-outcome
    - RATE=$(grep "Your code has been rated" /tmp/pylint-outcome |awk '{print $7}'|grep -o '[0-9]\+.[0-9]\+')
    - if [ $(echo "$RATE > 8" |bc) -eq 1 ]; then exit 0;else exit 1;fi
    # Report coverage
    - coverage report --omit=/usr/*,/home/travis/virtualenv/*
services:
    - rabbitmq
    - redis-server
before_script:
    - sudo mkdir /var/log/jasmin
    - sudo chown `whoami` /var/log/jasmin
    - sudo ln -s `pwd`/misc/config /etc/jasmin
    - sudo chown `whoami` /etc/jasmin/store
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-dev
    - sudo apt-get install -qq pylint
    - sudo apt-get install -qq bc
