language: python
python:
    - "2.7"
# Command to install dependencies
install:
    - pip install -r requirements
    - export PYTHONPATH=$PYTHONPATH:$(cd `pwd`;cd ..;pwd)
# Commands to run tests
script:
    # Normal tests
    - coverage run `which trial` jasmin
    # Docs building test
    - cd misc/doc;make html;cd ../../
    # Report coverage
    - coverage report --omit=/usr/*,/home/travis/virtualenv/*
    # Pylint code analysis and rating
    - export PYLINTRC=./misc/pylint/pylintrc
    - chmod +x ./misc/pylint/run.sh
    - ./misc/pylint/run.sh
services:
    - rabbitmq
    - redis-server
before_script:
    - sudo mkdir /var/log/jasmin
    - sudo chown `whoami` /var/log/jasmin
    - sudo ln -s `pwd`/misc/config /etc/jasmin
    - sudo chown `whoami` /etc/jasmin/store
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-dev
    - sudo apt-get install -qq pylint
    - sudo apt-get install -qq bc
