language: python
python:
    - "2.6"
    - "2.7"
# command to install dependencies
install: "pip install -r REQUIREMENTS"
# command to run tests
script: trial jasmin
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install rabbitmq-server redis-server python-twisted python-pip
    - sudo service rabbitmq-server start
    - sudo service redis-server start
