language: python
python:
    - "2.6"
    - "2.7"
# Command to install dependencies
install:
    - pip install -r REQUIREMENTS
    - export PYTHONPATH=$PYTHONPATH:/home/travis/build/fourat
# Commands to run tests
script:
    # Normal tests
#    - trial jasmin
    - trial jasmin.queues.test.test_amqp.ConnectTestCase
    # Docs building test
    - ls -l
    - cd misc/docs;ls -l;make html
services:
    - rabbitmq
    - redis-server
before_script:
    - sudo mkdir /var/log/jasmin;sudo chown `whoami` /var/log/jasmin
