language: python
python:
    - "2.7"
# Command to install dependencies
install:
    - python setup.py sdist
    - pip install dist/jasmin-0.4.0-alpha.tar.gz
# Commands to run tests
script:
    # Normal tests
    - coverage run `which trial` jasmin
    # Docs building test
    - cd misc/doc;make html;cd ../../
    # Report coverage
    - coverage report --omit=/usr/*,/home/travis/virtualenv/*
    # Pylint code analysis and rating
    - ./misc/pylint/run.sh
services:
    - rabbitmq
    - redis-server
before_script:
    # Test requirements
    - pip install -r test-requirements
    # pylint requirements
    - sudo apt-get install -qq pylint bc
    - export PYLINTRC=./misc/pylint/pylintrc
    - chmod +x ./misc/pylint/run.sh
before_install:
    - sudo apt-get update -qq
    # jasmin requirement
    - sudo apt-get install -qq python-dev libffi-dev libssl-dev
    - sudo mkdir -p /var/log/jasmin /etc/jasmin /etc/jasmin/resources /etc/jasmin/store
    - sudo chown `whoami` /var/log/jasmin /etc/jasmin /etc/jasmin/resources /etc/jasmin/store
