sudo: false
language: python
python:
    - '2.7'
env:
    - ROOT_PATH=~/jasmin JASMIN_RELEASE=0.9.25
# Command to install dependencies
install:
    - python setup.py sdist
    - pip install "dist/jasmin-$JASMIN_RELEASE.tar.gz"
# Commands to run tests:
script:
    #- coverage run `which trial` jasmin.managers.test.test_managers.AuthenticatedTestCases.test_connect_failure
    - echo $ROOT_PATH
    - ls -l $ROOT_PATH
    - cat $ROOT_PATH/var/log/jasmin/*
services:
    - rabbitmq
    - redis-server
before_script:
    - pip install -r test-requirements
before_install:
    - virtualenv venv
    - source venv/bin/activate
    - mkdir -p $ROOT_PATH/var/log/jasmin
    - mkdir -p $ROOT_PATH/etc/jasmin/resource
    - mkdir -p $ROOT_PATH/etc/jasmin/init-script
    - mkdir -p $ROOT_PATH/etc/jasmin/store
    - mkdir -p $ROOT_PATH/etc/init.d
    - chmod -R 777 $ROOT_PATH/var/log/jasmin $ROOT_PATH/etc/jasmin/store
addons:
  apt:
    packages:
    # jasmin installation requirement:
    # As documented here http://docs.jasminsms.com/en/latest/installation/index.html
    - python-dev
    - libffi-dev
    - libssl-dev
    - bc
